networks:
  default:
    name: my-network

services:

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # 🔹 Mode KRaft
      CLUSTER_ID: "qtU3_Z7ST66u8S69m09C-g"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      
      # 🔹 Listener configuration
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      # 🔹 Storage
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"

      # 🔹 Replication (dev mode)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: always

  raw-db:
    image: mongo:6
    container_name: raw-db
    volumes:
      - raw_data:/data/db
    restart: always

  ingestion-service:
    build: ./data-pipeline/ingestion
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - All
    cap_add:
      - NET_BIND_SERVICE 
    depends_on:
      redis:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_BROKER=kafka:9092
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    restart: always

  # preprocessing-service:
  #   build: ./data-pipline/pre-processing
  #   security_opt:
  #     - no-new-privileges:true
  #   cap_drop:
  #     - All
  #   cap_add:
  #     - NET_BIND_SERVICE
  #   depends_on:
  #     - kafka
  #     - raw-db
  #   environment:
  #     - KAFKA_BROKER=kafka:9092
  #     - RAW_DB_URI=mongodb://raw-db:27017
  #   restart: always

  # normalization-service:
  #   build: ./data-pipline/normalization
  #   security_opt: 
  #     - no-new-privileges:true
  #   cap_drop: 
  #     - All
  #   cap_add:  
  #     - NET_BIND_SERVICE
  #   depends_on:
  #     - kafka
  #     - final-db
  #   environment:
  #     - KAFKA_BROKER=kafka:9092
  #     - FINAL_DB_URI=postgresql://postgres:password@final-db:5432/jobs
  #   restart: always

  final-db:
    image: postgres:15
    container_name: final-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobs
    volumes:
      - final_data:/var/lib/postgresql/data
    restart: always
  
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

# ----------------------------
# 🔹 Volumes (Déclarations)
# ----------------------------
volumes:
  kafka_data:
  raw_data:
  final_data:
  redis_data: